### ISSUE TITLE
"extgui" not declared in logmsg.c

### ISSUE THREAD

**Issue by PeterCoghlan** [hercules-390/hyperion#150]
I get the following error when compiling logmsg.c without EXTERNALGUI being defined:

       if (sysblk.shutdown && !extgui)
................................^
%CC-E-UNDECLARED, In this statement, "extgui" is not declared at line number 464 in file logmsg.c

extgui appears in lots of other code without any issues.  It appears that use of it should be protected by #ifdef EXTERNALGUI or similar.

**Comment by Fish-Git** [comment]
Actually now might be a good time to make `EXTERNALGUI` permanent (i.e. remove the build option altogether).

Since external GUIs have been available not only on Windows but also on non-Windows (*nix) platforms too for quite some time now (which was why `--enable-external-gui` was made the default configure.ac build option quite some time ago), Hercules should simply _always_ be built with external GUI support.  That is to say, I personally don't see much of an advantage to building Hercules _without_ external GUI support.

**Comment by PeterCoghlan** [comment]
I can confirm that the problem I reported goes away when I compile with EXTERNALGUI defined.  I've looked briefly through the code that gets excluded when EXTERNALGUI is not defined and I didn't spot anything likely to cause difficulties if it is included all the time.  I guess any lurking problems would have been found by now anyway as everyone else has been compiling that way for some time.

**Comment by truda** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I do have experienced this problem all the time but I've simply have out commented the offending code (if statement) since I always compile without the gui. Personally I prefer the option remains but then who am I.
Regards,Gert


Verzonden van Yahoo Mail voor iPhone


Op vrijdag, september 2, 2016, 4:42 PM, PeterCoghlan <notifications@github.com> schreef:


I've looked briefly through the code that gets excluded when EXTERNALGUI is not defined and I didn't spot anything likely to cause difficulties if it is included all the time. I guess any lurking problems would have been found by now anyway as everyone else has been compiling that way for some time.

**Comment by Fish-Git** [comment]
> Personally I prefer the option remains but then who am I.

A Herculean whose opinion carries weight? &nbsp;`:)`

The option stays.  I'll fix the code.
