### ISSUE TITLE
Invalid device serial number

### ISSUE THREAD

**Issue by Fish-Git** [hercules-390/hyperion#16]
*INVALID* DEV-SERIAL bug:

ds qd,a80,attr,rdc                                

 UNIT VOLSER SCUTYPE DEVTYPE       CYL  SSID SCU-SERIAL DEV-SERIAL EFC  
00A80 ZDRES1 39900E9 339000A      3339  0A80 XXZZ-00001 *INVALID*  *OK

  ATTRIBUTE/FEATURE        YES/NO    ATTRIBUTE/FEATURE        YES/NO    
  SOLID STATE DRIVES          N      ENCRYPTION                  N      

  READ DEVICE CHARACTERISTIC                                            

3990E933900A5000 101020240D0B000F E000E5A205940222 1309067400000000     
0000000000000000 24241502DFEE0001 0677080F007F4800 15FF000000000000     

This is likely a NED/NEQ problem.  I believe we are currently using zero for all of our serial numbers, which is wrong.

I think we may need to design some way for each component of each node to be properly assigned its own unique (stable/unchanging?) serial number.

**Comment by Fish-Git2** [comment]
FYI: issue #64 is a duplicate of this one, but since github does not support merging two separate issues together into just one issue, I am keeping both github issues separate from one another since the other issue (#64) contains additional helpful information.

When either github issue is closed the responsible party should take care to also close the other github issue too.

**Comment by Fish-Git** [comment]
Issue #64 closed, so am closing this issue too.
