### ISSUE TITLE
compiled Hyperion from github. Hercules freezes at startup for a very long time (> 10 min), then starts fine

### ISSUE THREAD

**Issue by moshix** [hercules-390/hyperion#266]
I have this weird problem, fully reproducible across systems of Hercules on Ubuntu 64bit - tried 14.04, 16.04 and 18.04):

compiles fine, when I launch any hercules.cnf which works with prior version of Hercules, Hyperion freezes waiting on something unknown. After about 10 minutes it finally does come up all the way to the familiar console screen. 

HHC00100I Thread id 00007fc93c10e700, prio 15, name Processor CP00 started
HHC00811I Processor CP00: architecture mode z/Arch
HHC02204I CPUSERIAL      set to 1232EF
HHC02204I CPUMODEL       set to 2097
HHC02204I CPUVERID       set to 00
HHC17003I MAIN     storage is 1536M (mainsize); storage is not locked
HHC00100I Thread id 00007fc937bd1700, prio -20, name Timer started
HHC00100I Thread id 00007fc937dd4700, prio 15, name Processor CP01 started
HHC00811I Processor CP01: architecture mode z/Arch
HHC02204I NUMCPU         set to 2
HHC02204I MANUFACTURER   set to IBM
HHC02204I MODEL          set to hardware(303) capacity(303) perm() temp()
HHC02204I ARCHLVL        set to z/Arch
HHC02256W Command ALRF is deprecated, use archlvl ENABLE asn_lx_reuse instead
HHC00892E Facility( asn_lx_reuse ) does not exist for z/Arch
HHC00887W Note: Enabling/Disabling/Querying facilities via 'ARCHLVL' is deprecated.
HHC00888W       Please use the new FACILITY command instead.
HHC01441E Config file[28] hercules.cnf: error processing statement: ALRF ENABLE
HHC00898W Facility( 044_PFPO ) *Enabled for z/Arch
HHC00887W Note: Enabling/Disabling/Querying facilities via 'ARCHLVL' is deprecated.
HHC00888W       Please use the new FACILITY command instead.
HHC00898I Facility( 045_DISTINCT_OPERANDS ) Enabled for z/Arch
HHC00887W Note: Enabling/Disabling/Querying facilities via 'ARCHLVL' is deprecated.
HHC00888W       Please use the new FACILITY command instead.
HHC00898I Facility( 037_FP_EXTENSION ) Enabled for z/Arch
HHC00887W Note: Enabling/Disabling/Querying facilities via 'ARCHLVL' is deprecated.
HHC00888W       Please use the new FACILITY command instead.
HHC02204I ECPSVM         set to disabled
HHC00346I cckd opts: comp=-1,compparm=-1,freepend=-1,fsync=0,gcint=10,gcparm=0
HHC00346I            linuxnull=0,nosfd=0,nostress=0,ra=6,raq=4,rat=2,trace=0,wr=3
HHC02204I LOADPARM       set to 0009
HHC02204I LPARNAME       set to SYSZ24
HHC02204I PANTITLE       set to z/VM 6.2 SYSRES 6200
HHC01474I Using internal codepage conversion table default
HHC02204I DIAG8CMD       set to ENABLE  NOECHO
HHC02204I PANRATE        set to SLOW
HHC00100I Thread id 00007fc937cd3700, prio  4, name Console connection started
HHC01024I Waiting for console connections on port 3270
HHC02915I client 0 COMM: Connection received
HHC02914I 0:0000 COMM: client 0 negotiations complete; ttype = 'IBM-3279-3-E'
HHC01018I 0:0000 COMM: client 127.0.0.1 devtype 3270: connected

**Comment by Fish-Git** [comment]
> when I launch any hercules.cnf which works with prior version of Hercules, Hyperion freezes waiting on something unknown. After about 10 minutes it finally does come up all the way to the familiar console screen.

. . .

> HHC00887W Note: Enabling/Disabling/Querying facilities via 'ARCHLVL' is deprecated.
> HHC00888W Please use the new FACILITY command instead.

The above warning messages tell me you are using the SDL version of Hercules 4.0 Hyperion, and not the Hercules-390 version of 4.0 Hyperion.

You are posting your GitHub Issue to the wrong project!

You should instead post your GitHub Issue to the [SDL-Hercules-390/hyperion](https://github.com/SDL-Hercules-390/hyperion) Issues page at https://github.com/SDL-Hercules-390/hyperion/issues/new.

(Oh. And by the way. The problem you describe [has already been identified and fixed](https://github.com/SDL-Hercules-390/hyperion/issues/120)(*). Please refresh and rebuild your copy of SDL Hyperion and try again. It should start up instantaneously this time.)
___
(*) The bug was the use of `dev/random` instead of `/dev/urandom` as well as an infinite timeout on a `poll` call in the logic that initializes the z/Architecture cryptographic "wrapping keys".
