### ISSUE TITLE
TCP_KEEPIDLE does *not* appear in the tcp.h included with OS X Yosemite (10.10.2; XCode 6.1.1)

### ISSUE THREAD

**Issue by dlrourke** [hercules-390/hyperion#45]
Because TCP_KEEPIDLE does not appear in the file tcp.h included with OS X Yosemite (10.10.2; XCode 6.1.1; Command Line Tools 6.1.1) compilation of hscutl.c fails.  Here is the relevant invocation of gcc (actually, clang) and associated error message:

 gcc -DHAVE_CONFIG_H -I. -I. -I./decNumber -I. -DPKGDATADIR=\"/usr/local/share/hercules\" -DMODULESDIR=\"/usr/local/lib/hercules\" -DHERC_LOCALEDIR=\"/usr/local/share/locale\" -W -Wall -g3 -ggdb3 -O3 -march=core2 -fomit-frame-pointer -MT hscutl.lo -MD -MP -MF .deps/hscutl.Tpo -c hscutl.c  -fno-common -DPIC -o .libs/hscutl.o
hscutl.c:824:33: error: use of undeclared identifier 'TCP_KEEPIDLE'
    if (getsockopt( sfd, l_tcp, TCP_KEEPIDLE,  &optval, &optlen ) >= 0) *idle_time      = optval;

**Comment by Fish-Git** [comment]
Fix devised. Testing in progress...

**Comment by Fish-Git** [comment]
Closed by commit 67975312c99fdceea05e9d46b56537784ea9abe7.

**Comment by Fish-Git** [comment]
(Oops!) I'm not done yet, folks! I forgot something. DON'T USE THIS VERSION! IT CRASHES! I will have it fixed VERY shortly. Hang loose. (And sorry about this!)

**Comment by Fish-Git** [comment]
NOW it should be working. Commit a0e40ebf25185deb907632e1cdf38a8d86a1d57e fixes previously mentioned crash on MSVC platforms due to an oversight on my part.

**Comment by dlrourke** [comment]
I compiled and ran this version on Linux Mint 14.1 (running inside VirtualBox on Windows 8.1) using MTS as the operating system and everything worked fine.  To compile, I did:
cd hyperion
sh ./autogen.sh
./configure --enable-cckd-bzip2 --enable-het-bzip2
make
su
make install
^D (to exit SU mode)
cd ../MTS
hercules

I use a freshly compiled version of c3270 which looks very, very nice on Linux Mint and Centos 6.6.

A little later today, I'll try this version out on OS X 10.10.2.

Thank you very, very much for this and you really do nice work!

Cordially,
Dan

**Comment by dlrourke** [comment]
Compiling the latest version of Hyperion in OS X 10.10.2 didn't work.  For reasons not yet clear to me, ptrdiff_t was not defined and you get an error when compiling "console.c.".  I'm using XCode 6.1.1 and the command line tools (also 6.1.1) along with autoconf, automake, etc., from MacPorts.

I don't think that you have access to a Mac system so let me see where ptrdiff_t is supposed to be defined on the Mac and see if it is.  The include to pick it up may not be the same on a Mac as it is on other Unix/Linux systems.  The Mac documentation is not terribly helpful is this regard so I'll probably end up using grep to track it down.

Sorry...

**Comment by Fish-Git** [comment]
Daniel Rourke wrote:

[...]
> Compiling the latest version of Hyperion in OS X
> 10.10.2 didn't work. For reasons not yet clear to me,
> ptrdiff_t was not defined and you get an error when
> compiling "console.c.". [...]

That's odd. As best I can tell, the 'ptrdiff_t' type has been a part of the C standard since about 1998.

And (again, as best I can tell), it has always been the "stddef.h" header that defines it.

This is pretty basic stuff.

Something doesn't sound right.

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com

**Comment by Fish-Git** [comment]
Daniel Rourke wrote:

[...]
> Incidentally, ptrdiff_t is used in only one line
> in all of Hyperion—in a change you made to console.c.

Hmmmm. And it seems we don't #include <stddef.h> anywhere either, except in one place: strsignal.c. Weird. I can't believe we've gone all these years without it! That's incredible.

Okay. Try this. Take OUT the #include that you added, and instead, change the cast from (ptrdiff_t) to (U64) instead:

  csock = (int)(U64)pArg;

Try that and tell me whether Apple like it or not.

Thanks.


(Sheesh! This is starting to turn into a never-ending project! :)

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com

**Comment by dlrourke** [comment]
> On Feb 1, 2015, at 12:43 AM, Fish-Git <notifications@github.com> wrote:
> 
> Daniel Rourke wrote: 
> 
> [...] 
> > Incidentally, ptrdiff_t is used in only one line 
> > in all of Hyperion—in a change you made to console.c. 
> 
> Hmmmm. And it seems we don't #include <stddef.h> anywhere either, except in one place: strsignal.c. Weird. I can't believe we've gone all these years without it! That's incredible. 
> 
> Okay. Try this. Take OUT the #include that you added, and instead, change the cast from (ptrdiff_t) to (U64) instead: 
> 
> csock = (int)(U64)pArg; 
> 
> Try that and tell me whether Apple like it or not. 
> 
> Thanks. 
> 

OK, I made the change you suggest above, but changed U64 to S64 because the difference between two pointers could be negative.  Hyperion compiled and ran fine, but please bear in mind that I run MTS, not MVS or VM.

Also, this will work on a 64 bit system, but not a 32 bit one.  If you don’t mind, let me see if I can figure out how to safely include stddef.h.  The whole point of using ptrdiff_t (and intptr_t, for that matter) is that they will have the appropriate size, depending on whether the system is a 32 or 64 bit one.

Cordially,
Dan

**Comment by herc4mac** [comment]
> On 02 Feb 2015, at 01:03, Daniel Rourke <notifications@github.com> wrote:
> 
> Also, this will work on a 64 bit system, but not a 32 bit one. If you don’t mind, let me see if I can figure out how to safely include stddef.h. The whole point of using ptrdiff_t (and intptr_t, for that matter) is that they will have the appropriate size, depending on whether the system is a 32 or 64 bit one. 
> 
> Cordially, 
> Dan 


quoting

ISO/IEC 9899:1990 (C89, C90)

The 15 standard headers in C89 are:

<assert.h>  <limits.h>  <signal.h>  <stdlib.h>
<ctype.h>   <locale.h>  <stdarg.h>  <string.h>
<errno.h>   <math.h>    <stddef.h>  <time.h>
<float.h>   <setjmp.h>  <stdio.h>
so there should be no problem in including stddef.h from hstdinc.h 

for a bit of overkill we might check for it in configure.ac in the required header section

but if You do not want to to include it You might properly define Yourself
the prtdiff  type by checking the size of void *
8 vs 4 and define accordingly

cheers
enrico

**Comment by Fish-Git** [comment]
Daniel Rourke wrote:
> Fish wrote:
[...]
> > Okay. Try this. Take OUT the #include that you added,
> > and instead, change the cast from (ptrdiff_t) to (U64)
> > instead:
> >
> >       csock = (int)(U64)pArg;
[...]
> OK, I made the change you suggest above, but changed U64
> to S64 because the difference between two pointers could
> be negative.

No. Wrong. There is no "pointer difference" involved. The value being passed is an ordinary integer (a socket file descriptor). It is simply being passed AS a void pointer, and the function receiving that void pointer argument is simply trying to convert it back to an integer again via truncation.


> Hyperion compiled and ran fine, but please bear in mind
> that I run MTS, not MVS or VM.

Immaterial. What does which guest you run have anything to do with trying to build Hercules on Apple? Answer: absolutely nothing.


> Also, this will work on a 64 bit system, but not a 32 bit
> one.

Wrong again.  :)


> If you don’t mind, let me see if I can figure out how to
> safely include stddef.h.

I don't mind. But you're wasting your time. Casting it to a (U64) and then to an (int) should work just fine with absolutely no side effects whatsoever, regardless of the build and/or runtime platform.


> The whole point of using ptrdiff_t (and intptr_t, for
> that matter) is that they will have the appropriate size,
> depending on whether the system is a 32 or 64 bit one.

Almost. The whole point for using ptrdiff_t or intptr_t is not so much that such types are the same SIZE as pointers, but more because they're simply NOT "pointers". They're just numbers.

Whether the number is signed or unsigned doesn't matter. Whether the number is 32-bits long or 64-bits long doesn't matter.

ALL we're trying to do is convert a 32-bit or 64-bit POINTER to a 32-bit INTEGER. Period. Nothing more, nothing less. We're simply trying to "chop off" the high order 32-bits if the pointer is a 64-bit pointer (or "chop off" the high order "0" bits if the pointer is a 32-bit pointer), and then tell the compiler to please start using it as an integer.

And we're trying to do it SOLELY to make brain-dead compilers understand that yes, we DO know what the fuck we're doing thankyouverymuch, and to please shut the fuck up about it and just DO IT already. :)

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: fish@softdevlabs.com
