### ISSUE TITLE
IPL failure with z/OS 1.10

### ISSUE THREAD

**Issue by 0x27** [hercules-390/hyperion#49]
Hey there,
So, I am getting the following output when I try 'ipl a80' my z/OS (version 1.10).

Output: (just as I run 'ipl a80'): https://gist.githubusercontent.com/0x27/ebca56634ecfc16098a1/raw/3a31caf81a5d1c0fb731bfd8c966eb3b53a2b8a3/gistfile1.txt

ADCD_LINUX.CONF: https://gist.github.com/0x27/7d3792138e104180408b (basically the example one with the suggested edits, ala http://pastebin.com/raw.php?i=umhdBsPu).

Anyways, was hoping someone would be able to give me a hand sorting this out. Have not a whole lot of proper experience with mainframes and such, however am thoroughly enjoying myself every time I get a chance to muck about with some Big Iron, so having some delicious delicious Big Iron on my localbox would be awesome for science :D

Edit, ah yes, setup details:
Host OS: x86_64 Linux 3.18.6-1-ARCH
Host CPU: Intel Core i7-2620M CPU @ 3.4GHz
Host RAM: 8Gb.

Edit 2: I am assuming the "host error" means something segfaulted in Hercules, if theres any configs or alterations I should make on the host side I will try that :)

**Comment by tljohnsn** [comment]
Did you ever figure this out?  I am having the same problem.

**Comment by 0x27** [comment]
Yes, actually. Another user helped me out by suggesting I do "./configure --enable-optimization=no", which results in a working build.

**Comment by ivan-w** [comment]
David,

The original segfault report was due to a non-aligned access to storage 
to the "mainframe" main storage.

When hercules is built without optimization, non-aligned stores on an 
Intel processor aren't an issue

When the compile is optimized, the compiler may elect to use the 
processor vector facilities which has an alignment constraint.

It wound out, non aligned access to storage by the latest C standard is 
not guaranteed to be "undefined" i.e. not to give a predictable result. 
So it was corrected to always be aligned such as we do for ARM (which 
command all accesses to be aligned).

The latest version of hercules *SHOULD* always use aligned access in 
respect to the host running hercules, so this should no longer happen.

If this still occurs with the latest version of hercules, then this 
should be investigated
