### ISSUE TITLE
REGRESSION: z/VM 6.2 LCS not working any more 

### ISSUE THREAD

**Issue by fbi-ranger** [hercules-390/hyperion#66]
Host environment: HERCULES / Hyperion 4.0 on openSUSE 13.2.
Guest O/S: z/VM 6.2 (RSU 1302)

Description: 
LCS definition which worked correctly yesterday, delivers now an weird channel error.

After IPL and tap0/tap1 (0F00/0F01) are opened correctly. However, Hercules messages showing which MACID is used are not displayed any more. TCP/IP connection via LCS does not become active any more. 
It delivers Channel Status 20 on UA 0F00. 

--
13:06:55 DTCSTM243I ******************************************
13:06:55 DTCSTM244I Log of IBM TCP/IP Telnet Server Users started on 09/18/15 at
 13:06:55
13:06:55 DTCSTM245I
13:06:55 DTCPC3083E PCCA3 device DEV§0F00: Unexpected CSW from SenseId command o
n device 0F00
13:06:55 DTCPRI461I    Keys: E0, CcwAddress: 077FB4F0
13:06:55 DTCPRI462I    Status bits: C0, SCFA: 4017
13:06:55 DTCPRI463I    Unit Status: 00, Channel Status: 20
13:06:55 DTCPRI464I    Byte Count:            0
13:06:55 DTCPRI470I    Subchannel Logout: 00800000
13:06:55 DTCPRI471I    Extended Report Word: 00000000
13:06:55 DTCPC3082E PCCA3 shutting down:
13:06:55 DTCPRI385I    Device DEV§0F00:
13:06:55 DTCPRI386I       Type: LCS, Status: Sense ID on input

**Comment by Fish-Git** [comment]
It's failing for me now too!  WTF?!

Let me look into it and get back to you...

**Comment by Fish-Git** [comment]
False alarm. Sorry.

LCS works just fine for me on Windows. (I was just doing something stupid.)

I have no idea (yet) why LCS no longer works for you on Linux. I honestly cannot see how any of the recent changes could in any way impact LCS devices! Something obviously changed on your system (with your Hercules) to cause it to break. We need to figure out what and why.

The only way to debug this issue is to enable CCW tracing and PTT tracing on your LCS devices. (We do _not_ to add the `debug` option -- _yet_)

Once you have your traces, then create a new GitHub "gist" (https://gist.github.com) for them, and insert the link (URL) into a comment here.

Thanks.

**Comment by fbi-ranger** [comment]
Hi Fish, 

At my side the problem is simply the known situation that sometimes the fu.. LCS is not properly initialized. 

Here are a CCW traces of the bad and good situation. 
https://gist.github.com/fbi-ranger/4d0fe2a8bc53665d535a

This is really a PITA. Yesterday I tried it about five times and it didn't work. Today the first time with trace was same situation, the next time was out of the sudden working. 

For me this issue can be closed

**Comment by Fish-Git** [comment]
I'm sorry to hear you are still having your "unreliable/inconsistent startup" problem with LCS devices (i.e. sometimes they work, sometimes they don't).

There must be something very subtle that IBM is doing that we (Hercules) is still not handling properly.

I sure wish we could figure it out!  :disappointed:

I will look closely at your logs (thank you!) to see if I can find anything unusual that might provide a clue to why it sometimes works and sometimes doesn't (but don't hold your breath!).

As requested, I am closing this issue.
